/**
 * mock-data/skills.ts
 * Mock technical skills for the student.
 * Replace with GET /api/skills when backend is ready.
 */
import { TechnicalSkill } from '../core/models';

export const MOCK_SKILLS: TechnicalSkill[] = [
  {
    id: '1',
    name: 'Java',
    proficiency: 75,
    level: 'Advanced',
    requiredForGoal: 80,
    gap: 5,
    status: 'Strong',
    category: 'Backend',
  },
  {
    id: '2',
    name: 'Spring Boot',
    proficiency: 45,
    level: 'Intermediate',
    requiredForGoal: 80,
    gap: 35,
    status: 'Needs Improvement',
    category: 'Backend',
  },
  {
    id: '3',
    name: 'Spring Security',
    proficiency: 30,
    level: 'Beginner',
    requiredForGoal: 75,
    gap: 45,
    status: 'Critical Gap',
    category: 'Backend',
  },
  {
    id: '4',
    name: 'REST API',
    proficiency: 50,
    level: 'Intermediate',
    requiredForGoal: 80,
    gap: 30,
    status: 'Needs Improvement',
    category: 'Backend',
  },
  {
    id: '5',
    name: 'Angular',
    proficiency: 60,
    level: 'Intermediate',
    requiredForGoal: 75,
    gap: 15,
    status: 'Needs Improvement',
    category: 'Frontend',
  },
  {
    id: '6',
    name: 'HTML/CSS',
    proficiency: 80,
    level: 'Advanced',
    requiredForGoal: 70,
    gap: 0,
    status: 'Strong',
    category: 'Frontend',
  },
  {
    id: '7',
    name: 'MySQL',
    proficiency: 70,
    level: 'Intermediate',
    requiredForGoal: 75,
    gap: 5,
    status: 'Strong',
    category: 'Database',
  },
  {
    id: '8',
    name: 'Git/GitHub',
    proficiency: 65,
    level: 'Intermediate',
    requiredForGoal: 70,
    gap: 5,
    status: 'Strong',
    category: 'DevOps',
  },
  {
    id: '9',
    name: 'Docker',
    proficiency: 20,
    level: 'Beginner',
    requiredForGoal: 65,
    gap: 45,
    status: 'Critical Gap',
    category: 'DevOps',
  },
];
